apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ggllrbspg-python
  janus-idp.io/tekton: ggllrbspg-python
  backstage.io/kubernetes-id: ggllrbspg-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ggllrbspg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
