apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ggllrbspg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ggllrbspg-python 
  name: ggllrbspg-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ggllrbspg-python
    weight: 100 
